In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder, OneHotEncoder
import pickle

In [2]:
df = pd.read_csv("Churn_Modelling.csv")
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [3]:
print(df.shape)

(10000, 14)

In [4]:
df = df.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1)
df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [5]:
label_encoder_gender = LabelEncoder()
df["Gender"] = label_encoder_gender.fit_transform(df["Gender"])
df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [6]:
one_hot_geo = OneHotEncoder()
geo_encoder= one_hot_geo.fit_transform(df[['Geography']]).toarray()
geo_encoder

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]], shape=(10000, 3))

In [7]:
one_hot_geo.get_feature_names_out(["Geography"])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [8]:
geo_encoded_df = pd.DataFrame(geo_encoder, columns=one_hot_geo.get_feature_names_out(["Geography"]))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [9]:
df = pd.concat([df.drop("Geography", axis=1), geo_encoded_df], axis=1)

In [10]:
df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,1,39,5,0.00,2,1,0,96270.64,0,1.0,0.0,0.0
9996,516,1,35,10,57369.61,1,1,1,101699.77,0,1.0,0.0,0.0
9997,709,0,36,7,0.00,1,0,1,42085.58,1,1.0,0.0,0.0
9998,772,1,42,3,75075.31,2,1,0,92888.52,1,0.0,1.0,0.0
9999,792,0,28,4,130142.79,1,1,0,38190.78,0,1.0,0.0,0.0

In [11]:
with open('label_encoder_gender.pkl', 'wb') as file:
    pickle.dump(label_encoder_gender,file)

with open('geo_encoder.pkl', 'wb') as file:
    pickle.dump(one_hot_geo, file)

In [12]:
from sklearn.preprocessing import StandardScaler

In [13]:
X = df.drop(["Exited"], axis=1)
y = df["Exited"]

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2,  random_state=42)
scalar = StandardScaler()
X_train = scalar.fit_transform(X_train)
X_test = scalar.transform(X_test)

In [15]:
print(X_train.shape)
print(X_test.shape)

print(y_train.shape)
print(y_test.shape)

(8000, 12)
(2000, 12)
(8000,)
(2000,)

In [16]:
X_train

array([[ 0.35649971,  0.91324755, -0.6557859 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.20389777,  0.91324755,  0.29493847, ..., -0.99850112,
         1.72572313, -0.57638802],
       [-0.96147213,  0.91324755, -1.41636539, ..., -0.99850112,
        -0.57946723,  1.73494238],
       ...,
       [ 0.86500853, -1.09499335, -0.08535128, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.15932282,  0.91324755,  0.3900109 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.47065475,  0.91324755,  1.15059039, ..., -0.99850112,
         1.72572313, -0.57638802]], shape=(8000, 12))

In [17]:
with open('scalar.pkl', 'wb') as file:
    pickle.dump(scalar, file)

In [18]:
%pip install tensorflow

Requirement already satisfied: tensorflow in c:\Users\Mithun\miniconda3\envs\ml\Lib\site-packages (2.21.0)
Requirement already satisfied: absl-py>=1.0.0 in c:\Users\Mithun\miniconda3\envs\ml\Lib\site-packages (from tensorflow) (2.5.1)
Requirement already satisfied: astunparse>=1.6.0 in c:\Users\Mithun\miniconda3\envs\ml\Lib\site-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=25.9.23 in c:\Users\Mithun\miniconda3\envs\ml\Lib\site-packages (from tensorflow) (25.12.19)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in c:\Users\Mithun\miniconda3\envs\ml\Lib\site-packages (from tensorflow) (0.7.0)
Requirement already satisfied: google_pasta>=0.1.1 in c:\Users\Mithun\miniconda3\envs\ml\Lib\site-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in c:\Users\Mithun\miniconda3\envs\ml\Lib\site-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt_einsum>=2.3.2 in c:\Users\Mithun\miniconda3\envs\ml\Lib\site-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in c:\Users\Mithun\miniconda3\envs\ml\Lib\site-packages (from tensorflow) (26.3)
Requirement already satisfied: protobuf<8.0.0,>=6.31.1 in c:\Users\Mithun\miniconda3\envs\ml\Lib\site-packages (from tensorflow) (7.36.2)
Requirement already satisfied: requests<3,>=2.21.0 in c:\Users\Mithun\miniconda3\envs\ml\Lib\site-packages (from tensorflow) (2.34.2)
Requirement already satisfied: setuptools in c:\Users\Mithun\miniconda3\envs\ml\Lib\site-packages (from tensorflow) (84.0.0)
Requirement already satisfied: six>=1.12.0 in c:\Users\Mithun\miniconda3\envs\ml\Lib\site-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in c:\Users\Mithun\miniconda3\envs\ml\Lib\site-packages (from tensorflow) (3.3.0)
Requirement already satisfied: typing_extensions>=3.6.6 in c:\Users\Mithun\miniconda3\envs\ml\Lib\site-packages (from tensorflow) (4.16.0)
Requirement already satisfied: wrapt>=1.11.0 in c:\Users\Mithun\miniconda3\envs\ml\Lib\site-packages (from tensorflow) (2.5.1)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in c:\Users\Mithun\miniconda3\envs\ml\Lib\site-packages (from tensorflow) (1.84.0)
Requirement already satisfied: keras>=3.12.0 in c:\Users\Mithun\miniconda3\envs\ml\Lib\site-packages (from tensorflow) (3.15.1)
Requirement already satisfied: numpy>=1.26.0 in c:\Users\Mithun\miniconda3\envs\ml\Lib\site-packages (from tensorflow) (2.5.3)
Requirement already satisfied: h5py<3.15.0,>=3.11.0 in c:\Users\Mithun\miniconda3\envs\ml\Lib\site-packages (from tensorflow) (3.14.0)
Requirement already satisfied: ml_dtypes<1.0.0,>=0.5.1 in c:\Users\Mithun\miniconda3\envs\ml\Lib\site-packages (from tensorflow) (0.6.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\Users\Mithun\miniconda3\envs\ml\Lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in c:\Users\Mithun\miniconda3\envs\ml\Lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.20)
Requirement already satisfied: urllib3<3,>=1.26 in c:\Users\Mithun\miniconda3\envs\ml\Lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2.8.0)
Requirement already satisfied: certifi>=2023.5.7 in c:\Users\Mithun\miniconda3\envs\ml\Lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2026.7.22)
Requirement already satisfied: wheel<1.0,>=0.23.0 in c:\Users\Mithun\miniconda3\envs\ml\Lib\site-packages (from astunparse>=1.6.0->tensorflow) (0.48.0)
Requirement already satisfied: rich in c:\Users\Mithun\miniconda3\envs\ml\Lib\site-packages (from keras>=3.12.0->tensorflow) (15.0.0)
Requirement already satisfied: namex in c:\Users\Mithun\miniconda3\envs\ml\Lib\site-packages (from keras>=3.12.0->tensorflow) (0.1.0)
Requirement already satisfied: optree in c:\Users\Mithun\miniconda3\envs\ml\Lib\site-packages (from keras>=3.12.0->tensorflow) (0.20.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\Users\Mithun\miniconda3\envs\ml\Lib\site-packages (from rich->keras>=3.12.0->tensorflow) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\Users\Mithun\miniconda3\envs\ml\Lib\site-packages (from rich->keras>=3.12.0->tensorflow) (2.21.0)
Requirement already satisfied: mdurl~=0.1 in c:\Users\Mithun\miniconda3\envs\ml\Lib\site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.12.0->tensorflow) (0.1.2)
Note: you may need to restart the kernel to use updated packages.

In [19]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

In [20]:
(X_train.shape[1],)

(12,)

In [21]:
model = Sequential(
    [
        Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
        Dense(32, activation='relu'),
        Dense(1, activation='sigmoid')

    ]
)

c:\Users\Mithun\miniconda3\envs\ml\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [22]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [23]:
%pip install tensorboard

Requirement already satisfied: tensorboard in c:\Users\Mithun\miniconda3\envs\ml\Lib\site-packages (2.21.0)
Requirement already satisfied: absl-py>=0.4 in c:\Users\Mithun\miniconda3\envs\ml\Lib\site-packages (from tensorboard) (2.5.1)
Requirement already satisfied: grpcio<2.0,>=1.74.0 in c:\Users\Mithun\miniconda3\envs\ml\Lib\site-packages (from tensorboard) (1.84.0)
Requirement already satisfied: markdown>=2.6.8 in c:\Users\Mithun\miniconda3\envs\ml\Lib\site-packages (from tensorboard) (3.11.1)
Requirement already satisfied: numpy>=1.12.0 in c:\Users\Mithun\miniconda3\envs\ml\Lib\site-packages (from tensorboard) (2.5.3)
Requirement already satisfied: packaging in c:\Users\Mithun\miniconda3\envs\ml\Lib\site-packages (from tensorboard) (26.3)
Requirement already satisfied: pillow in c:\Users\Mithun\miniconda3\envs\ml\Lib\site-packages (from tensorboard) (12.3.0)
Requirement already satisfied: protobuf<8.0.0,>=6.31.1 in c:\Users\Mithun\miniconda3\envs\ml\Lib\site-packages (from tensorboard) (7.36.2)
Requirement already satisfied: setuptools>=41.0.0 in c:\Users\Mithun\miniconda3\envs\ml\Lib\site-packages (from tensorboard) (84.0.0)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in c:\Users\Mithun\miniconda3\envs\ml\Lib\site-packages (from tensorboard) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in c:\Users\Mithun\miniconda3\envs\ml\Lib\site-packages (from tensorboard) (3.1.9)
Requirement already satisfied: typing-extensions~=4.12 in c:\Users\Mithun\miniconda3\envs\ml\Lib\site-packages (from grpcio<2.0,>=1.74.0->tensorboard) (4.16.0)
Requirement already satisfied: markupsafe>=2.1.1 in c:\Users\Mithun\miniconda3\envs\ml\Lib\site-packages (from werkzeug>=1.0.1->tensorboard) (3.0.3)
Note: you may need to restart the kernel to use updated packages.

In [24]:
import tensorflow
opt = tensorflow.keras.optimizers.Adam(learning_rate = 0.01)
loss = tensorflow.keras.losses.BinaryCrossentropy()
loss

In [25]:
model.compile(optimizer = opt, loss = loss, metrics=['accuracy'])

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [26]:
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard

log_dir="logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensor_callbacks = TensorBoard(log_dir= log_dir, histogram_freq=1)

In [27]:
early_stopping_callback = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

In [28]:
history = model.fit(
    X_train, y_train, validation_data = (X_test, y_test), epochs = 100, 
    callbacks =[tensor_callbacks, early_stopping_callback]
)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8313 - loss: 0.4019 - val_accuracy: 0.8540 - val_loss: 0.3547
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8544 - loss: 0.3577 - val_accuracy: 0.8605 - val_loss: 0.3407
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8600 - loss: 0.3456 - val_accuracy: 0.8620 - val_loss: 0.3447
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8601 - loss: 0.3410 - val_accuracy: 0.8540 - val_loss: 0.3494
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8637 - loss: 0.3382 - val_accuracy: 0.8550 - val_loss: 0.3437
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8619 - loss: 0.3362 - val_accuracy: 0.8605 - val_loss: 0.3370
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8625 - loss: 0.3370 - val_accuracy: 0.8555 - val_loss: 0.3562
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8641 - loss: 0.3364 - val_accuracy: 0.8610 - val_loss: 0.3548
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8635 - loss: 0.3337 - val_accuracy: 0.8540 - val_loss: 0.3474
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8639 - loss: 0.3314 - val_accuracy: 0.8595 - val_loss: 0.3398
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8640 - loss: 0.3287 - val_accuracy: 0.8575 - val_loss: 0.3577
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8665 - loss: 0.3275 - val_accuracy: 0.8585 - val_loss: 0.3511
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8664 - loss: 0.3272 - val_accuracy: 0.8585 - val_loss: 0.3441
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8694 - loss: 0.3224 - val_accuracy: 0.8620 - val_loss: 0.3569
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8659 - loss: 0.3227 - val_accuracy: 0.8625 - val_loss: 0.3477
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8696 - loss: 0.3181 - val_accuracy: 0.8645 - val_loss: 0.3418

In [29]:
model.save('model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [30]:
%load_ext tensorboard

In [31]:
%tensorboard --logdir logs/fit

ERROR: Could not find `tensorboard`. Please ensure that your PATH
contains an executable `tensorboard` program, or explicitly specify
the path to a TensorBoard binary by setting the `TENSORBOARD_BINARY`
environment variable.

In [32]:
import sys
import tensorboard

print("Python executable:", sys.executable)
print("TensorBoard version:", tensorboard.__version__)
print("TensorBoard location:", tensorboard.__file__)

Python executable: c:\Users\Mithun\miniconda3\envs\ml\python.exe
TensorBoard version: 2.21.0
TensorBoard location: c:\Users\Mithun\miniconda3\envs\ml\Lib\site-packages\tensorboard\__init__.py

In [33]:
%load_ext tensorboard

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

In [34]:
import sys
import subprocess

subprocess.Popen([
    sys.executable,
    "-m",
    "tensorboard.main",
    "--logdir", "logs/fit",
    "--port", "6006"
])